# Generated by Django 4.2.15 on 2024-08-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_techer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='techer',
            name='cv',
            field=models.FileField(default='l', upload_to='CV'),
            preserve_default=False,
        ),
    ]
