# Generated by Django 5.1 on 2024-08-16 08:09

import delivery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0005_alter_techer_cv"),
    ]

    operations = [
        migrations.AddField(
            model_name="techer",
            name="acceptaiton",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="techer",
            name="age",
            field=models.PositiveSmallIntegerField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="techer",
            name="demo",
            field=models.FileField(
                default=1, upload_to=delivery.models.demo_upload_path
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="techer",
            name="exams",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="techer",
            name="favoirates",
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="techer",
            name="group",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="techer",
            name="lessons",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="techer",
            name="period",
            field=models.DateField(default='2024-12-30'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="techer",
            name="section",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="techer",
            name="cv",
            field=models.FileField(upload_to=delivery.models.cv_upload_path),
        ),
    ]
