# Generated by Django 5.1 on 2024-08-16 08:21

import delivery.models
import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("delivery", "0006_techer_acceptaiton_techer_age_techer_demo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("phone", models.CharField(max_length=11)),
                ("age", models.PositiveSmallIntegerField(max_length=100)),
                ("stage", models.CharField(max_length=20)),
                ("section", models.CharField(max_length=20)),
                ("exams", models.CharField(max_length=20)),
                ("group", models.CharField(max_length=20)),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("reting", models.CharField(max_length=5)),
                (
                    "certification",
                    models.FileField(upload_to=delivery.models.certificate_upload_path),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="techer",
            name="reting",
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
