# Generated by Django 5.1 on 2024-08-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0007_student_techer_reting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="age",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="techer",
            name="age",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "student",
                    models.ManyToManyField(
                        related_name="students", to="delivery.student"
                    ),
                ),
                (
                    "techer",
                    models.ManyToManyField(
                        related_name="techers", to="delivery.techer"
                    ),
                ),
            ],
        ),
    ]
