# Generated by Django 5.1 on 2024-08-16 08:42

import delivery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0008_alter_student_age_alter_techer_age_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="stage",
            name="age",
            field=models.PositiveSmallIntegerField(
                choices=delivery.models.age_choises, default=1
            ),
            preserve_default=False,
        ),
    ]
