# Generated by Django 5.1 on 2024-08-16 08:57

import delivery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0009_stage_age"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stage",
            old_name="age",
            new_name="age_end",
        ),
        migrations.AddField(
            model_name="stage",
            name="age_start",
            field=models.PositiveSmallIntegerField(
                choices=delivery.models.age_choises, default=8
            ),
            preserve_default=False,
        ),
    ]
