# Generated by Django 5.1 on 2024-08-16 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0010_rename_age_stage_age_end_stage_age_start"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stage",
            name="student",
        ),
        migrations.RemoveField(
            model_name="stage",
            name="techer",
        ),
        migrations.AddField(
            model_name="stage",
            name="student",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students",
                to="delivery.student",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stage",
            name="techer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="techers",
                to="delivery.techer",
            ),
            preserve_default=False,
        ),
    ]
