# Generated by Django 5.1 on 2024-08-16 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0012_alter_stage_student_alter_stage_techer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stage",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students",
                to="delivery.student",
            ),
        ),
        migrations.AlterField(
            model_name="stage",
            name="techer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="techers",
                to="delivery.techer",
            ),
        ),
    ]
