# Generated by Django 5.1 on 2024-08-16 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0013_alter_stage_student_alter_stage_techer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stage",
            name="student",
        ),
        migrations.RemoveField(
            model_name="stage",
            name="techer",
        ),
        migrations.RemoveField(
            model_name="techer",
            name="favoirates",
        ),
        migrations.AddField(
            model_name="techer",
            name="stage",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="delivery.stage",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="delivery.stage"
            ),
        ),
    ]
