# Generated by Django 5.1 on 2024-08-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0015_exam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="duration",
            field=models.TimeField(),
        ),
    ]
