# Generated by Django 5.1 on 2024-08-16 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0016_alter_exam_duration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="techer",
            old_name="group",
            new_name="groub",
        ),
    ]
