# Generated by Django 5.1 on 2024-08-16 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0017_rename_group_techer_groub"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Techer",
        ),
    ]
