# Generated by Django 5.1 on 2024-08-16 15:00

import delivery.models
import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("delivery", "0018_delete_techer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Techer",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("phone", models.CharField(max_length=11)),
                ("age", models.PositiveSmallIntegerField()),
                ("acceptaiton", models.BooleanField(default=False)),
                ("section", models.CharField(max_length=20)),
                ("exams", models.CharField(max_length=20)),
                ("cv", models.FileField(upload_to=delivery.models.cv_upload_path)),
                ("demo", models.FileField(upload_to=delivery.models.demo_upload_path)),
                ("groub", models.CharField(max_length=20)),
                ("period", models.DateField()),
                ("reting", models.CharField(max_length=5)),
                ("lessons", models.CharField(max_length=20)),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="delivery.stage"
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
