# Generated by Django 5.1 on 2024-08-16 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0019_techer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="techer",
            name="stage",
        ),
        migrations.RemoveField(
            model_name="techer",
            name="user_ptr",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
        migrations.DeleteModel(
            name="Techer",
        ),
    ]
