# Generated by Django 5.1 on 2024-08-16 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0020_remove_techer_stage_remove_techer_user_ptr_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Exam",
        ),
        migrations.DeleteModel(
            name="Stage",
        ),
    ]
