# Generated by Django 5.1 on 2024-08-16 16:50

import coursation.models
import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("total", models.SmallIntegerField()),
                ("degree", models.SmallIntegerField()),
                ("duration", models.TimeField()),
                ("question", models.TextField()),
                ("answer", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "age_start",
                    models.PositiveSmallIntegerField(
                        choices=coursation.models.age_choises
                    ),
                ),
                (
                    "age_end",
                    models.PositiveSmallIntegerField(
                        choices=coursation.models.age_choises
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("phone", models.CharField(max_length=11)),
                ("age", models.PositiveSmallIntegerField()),
                ("section", models.CharField(max_length=20)),
                ("exams", models.CharField(max_length=20)),
                ("group", models.CharField(max_length=20)),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("reting", models.CharField(max_length=5)),
                (
                    "certification",
                    models.FileField(
                        upload_to=coursation.models.certificate_upload_path
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="coursation.stage",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Techer",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("phone", models.CharField(max_length=11)),
                ("age", models.PositiveSmallIntegerField()),
                ("acceptaiton", models.BooleanField(default=False)),
                ("section", models.CharField(max_length=20)),
                ("exams", models.CharField(max_length=20)),
                ("cv", models.FileField(upload_to=coursation.models.cv_upload_path)),
                (
                    "demo",
                    models.FileField(upload_to=coursation.models.demo_upload_path),
                ),
                ("groub", models.CharField(max_length=20)),
                ("period", models.DateField()),
                ("reting", models.CharField(max_length=5)),
                ("lessons", models.CharField(max_length=20)),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="coursation.stage",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
