# Generated by Django 5.1 on 2024-08-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "coursation",
            "0002_alter_techer_age_alter_techer_cv_alter_techer_demo_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="techer",
            name="activation",
            field=models.BooleanField(default=False),
        ),
    ]
