# Generated by Django 4.2.15 on 2024-08-19 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursation', '0003_alter_student_user_alter_techer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groub',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='coursation.student'),
        ),
        migrations.AlterField(
            model_name='groub',
            name='lesson',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='groub',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coursation.techer'),
        ),
    ]
