# Generated by Django 4.2.15 on 2024-08-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursation', '0003_student_first_name_student_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
