# Generated by Django 5.1 on 2024-08-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coursation", "0003_techer_activation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="techer",
            name="age",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
