# Generated by Django 4.2.15 on 2024-08-18 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursation', '0004_alter_student_first_name_alter_student_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techer',
            name='groub',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
