# Generated by Django 5.1 on 2024-08-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coursation", "0004_alter_techer_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="techer",
            name="age",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
