# Generated by Django 4.2.15 on 2024-08-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursation', '0005_lessson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groub',
            name='lesson',
        ),
        migrations.AddField(
            model_name='groub',
            name='lesson',
            field=models.ManyToManyField(null=True, to='coursation.lessson'),
        ),
    ]
