# Generated by Django 4.2.15 on 2024-08-18 17:42

import coursation.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursation', '0005_remove_techer_groub_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=11)),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('exams', models.CharField(max_length=20, null=True)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('reting', models.CharField(max_length=5, null=True)),
                ('certification', models.FileField(upload_to=coursation.models.certificate_upload_path)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='coursation.section')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='coursation.stage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
