# Generated by Django 5.1 on 2024-08-17 14:52

import coursation.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coursation", "0006_alter_techer_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="techer",
            name="cv",
            field=models.FileField(
                null=True, upload_to=coursation.models.cv_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="techer",
            name="demo",
            field=models.FileField(
                null=True, upload_to=coursation.models.demo_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="techer",
            name="exams",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="techer",
            name="groub",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="techer",
            name="lessons",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="techer",
            name="period",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="techer",
            name="reting",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="techer",
            name="section",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="techer",
            name="stage",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="coursation.stage",
            ),
        ),
    ]
