# Generated by Django 5.1 on 2024-08-23 09:59

import coursation.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coursation", "0006_remove_groub_lesson_groub_lesson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groub",
            name="count",
            field=models.SmallIntegerField(
                help_text="the number of student that you want to learn thim in this group"
            ),
        ),
        migrations.AlterField(
            model_name="groub",
            name="name",
            field=models.CharField(help_text="the name of the group", max_length=20),
        ),
        migrations.AlterField(
            model_name="techer",
            name="cv",
            field=models.FileField(
                help_text="upload a cv in pdf format",
                null=True,
                upload_to=coursation.models.cv_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="techer",
            name="demo",
            field=models.FileField(
                help_text="upload a short video in mp4 format to intrduse your self and of your shar7",
                null=True,
                upload_to=coursation.models.demo_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                    (11, 11),
                    (12, 12),
                    (13, 13),
                    (14, 14),
                    (15, 15),
                    (16, 16),
                    (17, 17),
                    (18, 18),
                    (19, 19),
                    (20, 20),
                    (21, 21),
                    (22, 22),
                    (23, 23),
                    (24, 24),
                    (25, 25),
                    (26, 26),
                    (27, 27),
                    (28, 28),
                    (29, 29),
                    (30, 30),
                    (31, 31),
                    (32, 32),
                    (33, 33),
                    (34, 34),
                    (35, 35),
                    (36, 36),
                    (37, 37),
                    (38, 38),
                    (39, 39),
                    (40, 40),
                    (41, 41),
                    (42, 42),
                    (43, 43),
                    (44, 44),
                    (45, 45),
                    (46, 46),
                    (47, 47),
                    (48, 48),
                    (49, 49),
                    (50, 50),
                    (51, 51),
                    (52, 52),
                    (53, 53),
                    (54, 54),
                    (55, 55),
                    (56, 56),
                    (57, 57),
                    (58, 58),
                    (59, 59),
                    (60, 60),
                    (61, 61),
                    (62, 62),
                    (63, 63),
                    (64, 64),
                    (65, 65),
                    (66, 66),
                    (67, 67),
                    (68, 68),
                    (69, 69),
                    (70, 70),
                    (71, 71),
                    (72, 72),
                    (73, 73),
                    (74, 74),
                    (75, 75),
                    (76, 76),
                    (77, 77),
                    (78, 78),
                    (79, 79),
                    (80, 80),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="section",
            field=models.ForeignKey(
                help_text="choose your subject",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="coursation.section",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="stage",
            field=models.ForeignKey(
                help_text="choose the stage you want to learn thim",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="coursation.stage",
            ),
        ),
    ]
