# Generated by Django 4.2.15 on 2024-08-18 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursation', '0006_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lesson', models.CharField(max_length=20)),
                ('count', models.SmallIntegerField()),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leader', to='coursation.student')),
                ('student', models.ManyToManyField(related_name='students', to='coursation.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
