# Generated by Django 5.1 on 2024-08-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "coursation",
            "0007_alter_groub_count_alter_groub_name_alter_techer_cv_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
