# Generated by Django 4.2.15 on 2024-08-18 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursation', '0007_remove_techer_groub_groub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groub',
            name='teacher',
        ),
        migrations.AddField(
            model_name='groub',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='teacher', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
