# Generated by Django 5.1 on 2024-08-17 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coursation", "0008_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="techer",
            name="section",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="coursation.section",
            ),
        ),
    ]
