# Generated by Django 4.2.15 on 2024-08-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursation', '0008_remove_groub_teacher_groub_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='groub',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
