# Generated by Django 4.2.15 on 2024-08-25 17:33

import coursation.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursation', '0009_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('units', models.CharField(max_length=2)),
                ('duration', models.CharField(max_length=20)),
                ('about', models.TextField()),
                ('cirtification', models.FileField(upload_to=coursation.models.certificate_upload_path)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('review', models.IntegerField(default=0)),
                ('skill', models.ManyToManyField(to='coursation.skills')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coursation.stage')),
                ('student', models.ManyToManyField(to='coursation.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coursation.techer')),
            ],
        ),
    ]
