# Generated by Django 4.2.15 on 2024-08-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursation', '0010_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='review',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
    ]
