# Generated by Django 4.2.15 on 2024-08-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursation', '0011_alter_course_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('goal', models.TextField()),
                ('incloude', models.FileField(upload_to='unit')),
            ],
        ),
    ]
