# Generated by Django 4.2.15 on 2024-08-18 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursation', '0011_rename_user_ptr_student_techer_ptr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='techer',
            old_name='reting',
            new_name='rating',
        ),
    ]
