# Generated by Django 4.2.15 on 2024-08-26 11:23

import coursation.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursation', '0012_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cirtification',
            field=models.FileField(null=True, upload_to=coursation.models.certificate_upload_path),
        ),
        migrations.AlterField(
            model_name='course',
            name='review',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(null=True, to='coursation.student'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='coursation.techer'),
        ),
    ]
