# Generated by Django 4.2.15 on 2024-08-26 14:32

import coursation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursation', '0014_remove_course_units_unit_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='incloude',
            field=models.FileField(upload_to=coursation.models.unit_files_upload_path),
        ),
    ]
