# Generated by Django 4.2.15 on 2024-08-26 15:10

import coursation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursation', '0014_remove_course_units_unit_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='incloude',
        ),
        migrations.AddField(
            model_name='unit',
            name='read',
            field=models.FileField(default=1, upload_to=coursation.models.unit_read_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='video',
            field=models.FileField(default=1, upload_to=coursation.models.unit_video_upload_path),
            preserve_default=False,
        ),
    ]
