# Generated by Django 4.2.15 on 2024-08-26 19:21

import coursation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursation', '0015_remove_unit_incloude_unit_read_unit_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessson',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='read',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='video',
        ),
        migrations.AddField(
            model_name='lessson',
            name='exam',
            field=models.ManyToManyField(to='coursation.exam'),
        ),
        migrations.AddField(
            model_name='lessson',
            name='read',
            field=models.FileField(default=1, upload_to=coursation.models.unit_read_upload_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessson',
            name='video',
            field=models.FileField(upload_to=coursation.models.unit_video_upload_path),
        ),
    ]
