# Generated by Django 4.2.15 on 2024-08-26 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursation', '0016_remove_lessson_resource_remove_unit_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessson',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coursation.unit'),
            preserve_default=False,
        ),
    ]
