# Generated by Django 4.2.15 on 2024-08-28 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursation', '0021_alter_lessson_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groub',
            name='lesson',
        ),
        migrations.DeleteModel(
            name='Lessson',
        ),
    ]
