# Generated by Django 4.2.15 on 2024-08-28 19:04

import coursation.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursation', '0022_remove_groub_lesson_delete_lessson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('topic', models.TextField()),
                ('video', models.FileField(upload_to=coursation.models.unit_video_upload_path)),
                ('read', models.FileField(upload_to=coursation.models.unit_read_upload_path)),
                ('exam', models.ManyToManyField(null=True, to='coursation.exam')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursation.unit')),
            ],
        ),
        migrations.AddField(
            model_name='groub',
            name='lesson',
            field=models.ManyToManyField(null=True, to='coursation.lesson'),
        ),
    ]
