# Generated by Django 4.2.15 on 2024-08-28 19:12

import coursation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursation', '0023_lesson_groub_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='read',
            field=models.FileField(blank=True, upload_to=coursation.models.unit_read_upload_path),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, upload_to=coursation.models.unit_video_upload_path),
        ),
    ]
