# Generated by Django 4.2.15 on 2024-09-04 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coursation", "0025_user_is_student_user_is_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="techer",
            name="lessons",
        ),
        migrations.RemoveField(
            model_name="techer",
            name="period",
        ),
    ]
