# Generated by Django 4.2.15 on 2024-09-04 19:58

import coursation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coursation", "0026_remove_techer_lessons_remove_techer_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="photo",
            field=models.ImageField(upload_to=coursation.models.course_photo_path),
        ),
    ]
