# Generated by Django 4.2.15 on 2024-09-04 20:00

import coursation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coursation", "0027_alter_course_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="photo",
            field=models.ImageField(
                null=True, upload_to=coursation.models.course_photo_path
            ),
        ),
    ]
