# Generated by Django 4.2.15 on 2024-09-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coursation", "0032_alter_user_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.PositiveSmallIntegerField(
                help_text="age 7 to 80 years", null=True
            ),
        ),
    ]
