# Generated by Django 4.2.15 on 2024-09-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coursation", "0033_alter_user_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
