# Generated by Django 4.2.15 on 2024-09-09 17:44

import coursation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coursation", "0034_alter_user_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="photo",
            field=models.FileField(
                default="static\\default.png",
                null=True,
                upload_to=coursation.models.course_photo_path,
            ),
        ),
    ]
